# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
        "iPhone SE",
        "iPhone 8",
        "iPhone 8 Plus",
        "iPhone Xs",
        "iPhone Xs Max",
        "iPad Pro (9.7-inch)",
        "iPad Pro (10.5-inch)",
        "iPad Pro (11-inch)",
        "iPad Pro (12.9-inch) (2nd generation)",
        "iPad Pro (12.9-inch) (3rd generation)",
        ])

languages([
          "en-US"
          ])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

reinstall_app true
clear_previous_screenshots true
number_of_retries 3
skip_open_summary true
ios_version "12.2"

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
